# Generated by Django 2.1.1 on 2018-10-08 00:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lims.models
import lims.utils.geometry
import lims.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', lims.models.SlugIdField(blank=True, db_index=True, max_length=55, validators=[django.core.validators.RegexValidator('[A-Za-z0-9._-]*')])),
                ('description', models.TextField(blank=True)),
                ('status', lims.models.LimsStatusField(choices=[('auto-draft', 'Auto Draft'), ('draft', 'Draft'), ('published', 'Published')], default='published', max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('recursive_depth', models.IntegerField(default=0, editable=False)),
                ('geometry', models.TextField(blank=True, validators=[lims.utils.geometry.validate_wkt])),
                ('geo_xmin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_xmax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('file', models.FileField(upload_to='attachments')),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('mime_type', models.CharField(blank=True, max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lims.Attachment')),
            ],
            options={
                'abstract': False,
            },
            bases=(lims.models.TagsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttachmentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('numeric_value', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('numeric_value_autoset', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('model', lims.models.LimsModelField(choices=[('Sample', 'Sample'), ('SampleTag', 'Sample Tag'), ('Attachment', 'Attachment'), ('AttachmentTag', 'Attachment Tag')], max_length=55)),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='last_used')),
            ],
        ),
        migrations.CreateModel(
            name='EntryTemplateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', models.CharField(blank=True, default='', max_length=55)),
                ('target', models.CharField(max_length=55)),
                ('initial_value', models.TextField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lims.EntryTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', lims.models.SlugIdField(blank=True, db_index=True, max_length=55, validators=[django.core.validators.RegexValidator('[A-Za-z0-9._-]*')])),
                ('description', models.TextField(blank=True)),
                ('status', lims.models.LimsStatusField(choices=[('auto-draft', 'Auto Draft'), ('draft', 'Draft'), ('published', 'Published')], default='published', max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('recursive_depth', models.IntegerField(default=0, editable=False)),
                ('geometry', models.TextField(blank=True, validators=[lims.utils.geometry.validate_wkt])),
                ('geo_xmin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_xmax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lims.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(lims.models.TagsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', lims.models.LimsModelField(choices=[('Sample', 'Sample'), ('SampleTag', 'Sample Tag'), ('Attachment', 'Attachment'), ('AttachmentTag', 'Attachment Tag')], max_length=55)),
                ('permission', models.CharField(choices=[('edit', 'Edit objects'), ('view', 'View objects')], max_length=55)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='lims.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lims_project_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('numeric_value', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('numeric_value_autoset', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('recursive_depth', models.IntegerField(default=0, editable=False)),
                ('geometry', models.TextField(blank=True, validators=[lims.utils.geometry.validate_wkt])),
                ('geo_xmin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_xmax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(default='sample', max_length=256)),
                ('slug', lims.models.SlugIdField(blank=True, db_index=True, max_length=55, unique=True, validators=[django.core.validators.RegexValidator('[A-Za-z0-9._-]*')])),
                ('collected', models.DateTimeField(default=django.utils.timezone.now, verbose_name='collected')),
                ('status', lims.models.LimsStatusField(choices=[('auto-draft', 'Auto Draft'), ('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=55)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lims.Sample')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lims.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(lims.models.TagsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SampleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('numeric_value', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('numeric_value_autoset', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(lims.models.TagsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SampleTagTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('numeric_value', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('numeric_value_autoset', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', lims.models.SlugIdField(blank=True, db_index=True, max_length=55, validators=[django.core.validators.RegexValidator('[A-Za-z0-9._-]*')])),
                ('description', models.TextField(blank=True)),
                ('status', lims.models.LimsStatusField(choices=[('auto-draft', 'Auto Draft'), ('draft', 'Draft'), ('published', 'Published')], default='published', max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('recursive_depth', models.IntegerField(default=0, editable=False)),
                ('geometry', models.TextField(blank=True, validators=[lims.utils.geometry.validate_wkt])),
                ('geo_xmin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_xmax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymin', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('geo_ymax', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('taxonomy', models.CharField(max_length=55)),
                ('measured', models.BooleanField(default=False)),
                ('input_widget_class', models.CharField(default='TextInput', max_length=55)),
                ('input_widget_arguments', models.TextField(blank=True, validators=[lims.validators.JSONDictValidator()])),
                ('output_widget_class', models.CharField(default='IdentityOutput', max_length=55)),
                ('output_widget_arguments', models.TextField(blank=True, validators=[lims.validators.JSONDictValidator()])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lims.Term')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='lims.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_terms', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(lims.models.TagsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TermTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('numeric_value', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('numeric_value_autoset', models.BooleanField(default=True, editable=False)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_tags', to='lims.Term')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='lims.Term')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_term_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('validator_class', models.CharField(max_length=55)),
                ('validator_arguments', models.TextField(blank=True, validators=[lims.validators.JSONDictValidator()])),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_validators', to='lims.Term')),
            ],
        ),
        migrations.AddField(
            model_name='sampletagtag',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_tag_tags', to='lims.Term'),
        ),
        migrations.AddField(
            model_name='sampletagtag',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='lims.SampleTag'),
        ),
        migrations.AddField(
            model_name='sampletagtag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_sample_tag_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampletag',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_tags', to='lims.Term'),
        ),
        migrations.AddField(
            model_name='sampletag',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='lims.Sample'),
        ),
        migrations.AddField(
            model_name='sampletag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_sample_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_tags', to='lims.Term'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='lims.Project'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_project_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrytemplate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='lims.Project'),
        ),
        migrations.AddField(
            model_name='entrytemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachmenttag',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_tags', to='lims.Term'),
        ),
        migrations.AddField(
            model_name='attachmenttag',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='lims.Attachment'),
        ),
        migrations.AddField(
            model_name='attachmenttag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_attachment_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='lims.Project'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='sample_tags',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='lims.SampleTag'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='lims.Sample'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='lims.Term'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lims_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('project', 'taxonomy', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='projectpermission',
            unique_together={('project', 'user', 'model', 'permission')},
        ),
    ]
