# Generated by Django 2.0.1 on 2018-01-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collected',
            field=models.DateTimeField(verbose_name='collected'),
        ),
    ]
