# Generated by Django 2.0.1 on 2018-02-28 22:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lims', '0002_sampleentrytemplatefield_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleentrytemplate',
            name='model',
            field=models.CharField(default='Sample', max_length=55, validators=[django.core.validators.RegexValidator('(Sample|SampleTag)')]),
        ),
        migrations.AddField(
            model_name='sampletag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='measured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lims.Term'),
        ),
    ]
