# Generated by Django 2.0.1 on 2018-01-31 20:44

from django.db import migrations, models
import lims.utils.geometry


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20180131_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='geometry',
            field=models.TextField(blank=True, validators=[lims.utils.geometry.validate_wkt]),
        ),
        migrations.AddField(
            model_name='sample',
            name='maxx',
            field=models.FloatField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='maxy',
            field=models.FloatField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='minx',
            field=models.FloatField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='miny',
            field=models.FloatField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='recursive_depth',
            field=models.IntegerField(default=0),
        ),
    ]
