# Generated by Django 2.0.1 on 2018-03-01 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20180228_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleentrytemplate',
            name='model',
            field=models.CharField(default='Sample', max_length=55, validators=[django.core.validators.RegexValidator('^(Sample|SampleTag|Location|LocationTag)$')]),
        ),
    ]
